apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMVENDQXBXZ0F3SUJBZ0lSQU8yUHUvSDRjcys1RldhZnlRMFRCVjh3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa05tWmlZbVEwT0RjdE5EazVaaTAwTmpjM0xUaGtNVE10WTJFeU0yUTRPVEZpTnpVMgpNQ0FYRFRJeU1URXlPVEl5TlRFME5Gb1lEekl3TlRJeE1USXhNak0xTVRRMFdqQXZNUzB3S3dZRFZRUURFeVEyClptSmlaRFE0TnkwME9UbG1MVFEyTnpjdE9HUXhNeTFqWVRJelpEZzVNV0kzTlRZd2dnR2lNQTBHQ1NxR1NJYjMKRFFFQkFRVUFBNElCandBd2dnR0tBb0lCZ1FETTEzdWVHUmhJQzVFd2YrWk1XTDQ1WURYc1p5OTdsbUNaWFQ0bAptN1pOelNES3FiT3IzTlR5eG56OHJGZUJtZnlVRXNaSEloMkhsU0NtMlpheG1YODBKN3k3UEhJSDBtdTlabXphCjg3NnpYaklMNWZrMHZRRk9iWi9nTkNtTWkzaDdXV1ltYVVIejU5cTF6OGxueVFVME8reHo2QVAwbmhac0tTOHMKNWJ4L0J4ekg0c0VVNGlPU3ArV3UxK1A1TnNxazhBc2N0MnV3NFVhSUN1RWhUREgwTC9HcjVBRG5SZElQUXIxTApYVlRPeUdZYWpsWnF1cStyb2FmdmJoS0FudEczZWdzdjBCV0IyenM4Y3RlRFZSaFBGRTdjQm5VY1IxWXNaZmVSCnkxOFJMWThVcHNyNzRmTlZnL3R2cnBweXZGYUdmYmRNUE5NN0p3bWVMZGc0bFQ0TEN0YTJBQ1ZqSG5FS2ZEM1IKVUt4MHBYTWprTzl3OEY1N1ROSzZxTUt1TmhIa0IrS1d5dkdJN2h4dnBHRFQ0cnNoazExOUhod3djdklJR3JqRApEcXoyRXJHSDF3dDRYYnlqSytDc0Z2WnY3cEIrNnlod1duYWVnei95ZWsrQjFXZ1N4cVNNR1NkQzNRVk51bkxyCnJ0QVNlSmdXSE82TDFJaFpROHFZWWh6dUdEOENBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdJRU1BOEcKQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGTnF1YmJxNTJ2a280VU9sckZYWUdxdG5nWit6TUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQmdRQTJzNTQwTEJSNmxaRkJZQU44Nzk2UmN4U3F6aHkzaUZLVFNNeVptQ3BBCjVVeHNNRjFQclVKNW5KdzJma3pXU0RaRXEvdHJmNnp2bE1uNEU3VE0wVWVPZzNxTlVJKy9GejhmWmhDcFZDdWgKeXYrVFpLeE5uWlI4M0pLblc3SkY3SEFhLzlNM2dmUWo3RXpXcjhsN0xCMlBjbXRWc3FhYlZuZzJETnM3RGZyTwozWU5XR0RuRnlHMkMyU1J1eDU4c05wMHVZL2wvaE1Ta3VaM0RZSXVzN1h5S1c1WWpWMmpWNnVtYVBWRzR2ZmxSCmQrN3kxMUM0dStqWjFnUkpPQ29wdzFielR3ejFvMk8xeTJFRWQ1a0JkM3N2OGFXM1ZWb1hqUGZISldDcTg1VE0KTTkvbnRCMGV0ZHNpTHduYVR6TFBGMElud1VJQUJ5eFVyTGliZVA5WG0xcVl6U2NxSjZDMjVSaGY3c0daKzc4SAp6dGx2ZW85UmZXRXlJcFZla1F6VzBRRnl1RWRYMit0Qi9NalB4WnpLcGNFQmQ3TTRKYzdOMkpEa04zOEpMVGxFCi80R3Y0SUNCbW9nU2FCZXp6ZFVscWNUa0pUaUFjSm04RGc5OEFTQ0l4QTFMbUxtMXhPTWkyZXdFWDI4bFN5MmQKZWpSUDVRL3ZGUnNpVnZSWmNBWHFraWs9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://35.237.155.34
  name: gke_dot-20221130004925_us-east1_dot
contexts:
- context:
    cluster: gke_dot-20221130004925_us-east1_dot
    user: gke_dot-20221130004925_us-east1_dot
  name: gke_dot-20221130004925_us-east1_dot
current-context: gke_dot-20221130004925_us-east1_dot
kind: Config
preferences: {}
users:
- name: gke_dot-20221130004925_us-east1_dot
  user:
    auth-provider:
      config:
        access-token: ya29.a0AeTM1iczWpjWOni8c-FJ0OjF93T7Spj1xv5A21r7ZpEbwsRY2P-G4k79tdX0l_X5qeGRDiifTXnUUeRrOLKK2JToR3z4Ol3L5Om9zi0jCBA-1imHzwM1Bf8fangKo5jne8l_rhnnzD_jxm4E9hqPAVPJUt4aVkOYDDQy3SAaCgYKAdcSAQ4SFQHWtWOmDROC2i8gExRlGfimWMs_aA0174
        cmd-args: config config-helper --format=json
        cmd-path: /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/gcloud
        expiry: "2022-11-30T02:09:28Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
