image:
  repository: harbor.sillydemo.com/library/cncf-demo
  tag: latest
ingress:
  host: dev.cncf-demo.sillydemo.com
tls:
  enabled: false
db:
  enabled: false
postgresql:
  global:
    persistence:
      enabled: false
  auth:
    postgresPassword: postgres
  primary:
    initdb:
      scripts:
        00_init_script.sh: |
          export PGPASSWORD=$POSTGRES_PASSWORD
          psql -U postgres -c 'CREATE DATABASE "cncf-demo";'
schemahero:
  enabled: false
