image:
  repository: harbor.sillydemo.com/library/cncf-demo
  tag: latest
ingress:
  host: dev.cncf-demo.sillydemo.com
tls:
  enabled: false
db:
  enabled: false
postgresql:
  global:
    persistence:
      enabled: false
  auth:
    postgresPassword: postgres
  initdbScripts:
    my_init_script.sh: |
      CREATE DATABASE "silly-demo";
schemahero:
  enabled: false
