---

apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQLClaim
metadata:
  name: cncf-demo
spec:
  id: cncf-demo-db-dev
  compositionSelector:
    matchLabels:
      provider: aws
      db: postgresql
  parameters:
    version: "13.4"
    size: small
