apiVersion: devopstoolkitseries.com/v1alpha1
kind: ClusterClaim
metadata:
  name: production
spec:
  id: production
  compositionSelector:
    matchLabels:
      provider: aws-official
      cluster: eks
  parameters:
    nodeSize: large
    minNodeCount: 3
    version: "1.24"
