apiVersion: devopstoolkitseries.com/v1alpha1
kind: ClusterClaim
metadata:
  name: production
spec:
  id: production
  compositionSelector:
    matchLabels:
      provider: aws
      cluster: eks
      version: 1.24
  parameters:
    nodeSize: medium
    minNodeCount: 3
