apiVersion: devopstoolkitseries.com/v1alpha1
kind: ClusterClaim
metadata:
  name: production
spec:
  id: production
  compositionSelector:
    matchLabels:
      provider: azure-official
      cluster: aks
  parameters:
    nodeSize: large
    minNodeCount: 3
