apiVersion: devopstoolkitseries.com/v1alpha1
kind: ClusterClaim
metadata:
  name: production
spec:
  id: production
  compositionSelector:
    matchLabels:
      provider: google-official
      cluster: gke
      version: 1.25.5-gke.1500
  parameters:
    nodeSize: medium
    minNodeCount: 1
