---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd
  namespace: argocd
spec:
  secretName: argocd
  issuerRef:
    kind: ClusterIssuer
    name: production
  commonName: argocd.sillydemo.com
  dnsNames:
    - argocd.sillydemo.com
