---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cncf-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    repoURL: https://github.com/devopsparadox/cncf-demo.git
    targetRevision: HEAD
    path: helm/app
    helm:
      releaseName: cncf-demo
      parameters:
        - name: image.tag
          value: latest
        - name: ingress.host
          value: cncf-demo.sillydemo.com
        - name: ingress.className
          value: nginx
        - name: tls.enabled
          value: "true"
        - name: db.enabled.google
          value: "false"
        - name: db.enabled.aws
          value: "false"
        - name: db.enabled.azure
          value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
