---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kbld.k14s.io/images: |
      - origins:
        - local:
            path: /Users/vfarcic/code/cncf-demo
        - git:
            dirty: true
            remoteURL: https://github.com/vfarcic/cncf-demo
            sha: 165843b048faadf49f91139399bb0978ae06fbf6
        url: kbld:cncf-demo-sha256-27fa99d8fddaf9ea47ea9aecb256906501ed12bf63517f3fb9f32786072b9f7f
  labels:
    app.kubernetes.io/name: cncf-demo
  name: cncf-demo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cncf-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cncf-demo
    spec:
      containers:
      - image: kbld:cncf-demo-sha256-27fa99d8fddaf9ea47ea9aecb256906501ed12bf63517f3fb9f32786072b9f7f
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        name: main
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
