apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure
spec:
  provider:
    azurekv:
      authType: ManagedIdentity
      vaultUrl: https://cncf-demo.vault.azure.net
