apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure
spec:
  provider:
    azurekv:
      tenantId: xxx
      vaultUrl: https://cncf-demo.vault.azure.net
      authSecretRef:
        clientId:
          name: azure
          key: ClientID
          namespace: external-secrets
        clientSecret:
          name: azure
          key: ClientSecret
          namespace: external-secrets
