---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: contour
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: contour
      version: 10.1.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  releaseName: contour
  targetNamespace: projectcontour
