---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: falco
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://falcosecurity.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: falco
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: falco
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: falco
        namespace: flux-system
  values:
    driver:
      kind: ebpf
    falcosidekick:
      enabled: true
    tty: true
  releaseName: falco
  targetNamespace: falco
  install:
    createNamespace: true
