---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: schema-hero
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./schema-hero
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: schemahero-system
