apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
images:
  - name: harbor.sillydemo.com/library/cncf-demo
    newName: harbor.sillydemo.com/library/cncf-demo
    newTag: latest
