apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- ingress.yaml
- service.yaml
images:
- name: docker.io/vfarcic/cncf-demo
  newName: docker.io/vfarcic/cncf-demo
  newTag: v0.0.1
