---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cncf-demo
spec:
  secretName: cncf-demo
  issuerRef:
    kind: ClusterIssuer
    name: production
  commonName: dev.cncf-demo.sillydemo.com
  dnsNames:
    - dev.cncf-demo.sillydemo.com
