---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cncf-demo
spec:
  template:
    spec:
      containers:
        - name: main
          env: 
          - name: DB_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: cncf-demo
                key: endpoint
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: cncf-demo
                key: port
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: cncf-demo
                key: username
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: cncf-demo
                key: password
          - name: DB_NAME
            value: cncf-demo
