#@ load("@ytt:data", "data")

#@ if data.values.tls.enabled:
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: #@ data.values.name
spec:
  secretName: #@ data.values.name
  issuerRef:
    kind: ClusterIssuer
    name: production
  commonName: #@ data.values.ingress.host
  dnsNames:
  - #@ data.values.ingress.host
#@ end