apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2023-01-17T17:25:44Z"
  generation: 1
  name: sqlclaims.devopstoolkitseries.com
  ownerReferences:
  - apiVersion: apiextensions.crossplane.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: CompositeResourceDefinition
    name: sqls.devopstoolkitseries.com
    uid: 5033b954-1d23-4808-8641-7a7a0070da85
  resourceVersion: "18162"
  uid: a997bc7c-6719-43a0-9729-7e863832902a
spec:
  conversion:
    strategy: None
  group: devopstoolkitseries.com
  names:
    categories:
    - claim
    kind: SQLClaim
    listKind: SQLClaimList
    plural: sqlclaims
    singular: sqlclaim
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=='Synced')].status
      name: SYNCED
      type: string
    - jsonPath: .status.conditions[?(@.type=='Ready')].status
      name: READY
      type: string
    - jsonPath: .spec.writeConnectionSecretToRef.name
      name: CONNECTION-SECRET
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: AGE
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              compositeDeletePolicy:
                default: Background
                enum:
                - Background
                - Foreground
                type: string
              compositionRef:
                properties:
                  name:
                    type: string
                required:
                - name
                type: object
              compositionRevisionRef:
                properties:
                  name:
                    type: string
                required:
                - name
                type: object
              compositionSelector:
                properties:
                  matchLabels:
                    additionalProperties:
                      type: string
                    type: object
                required:
                - matchLabels
                type: object
              compositionUpdatePolicy:
                default: Automatic
                enum:
                - Automatic
                - Manual
                type: string
              id:
                description: Database ID
                type: string
              parameters:
                properties:
                  size:
                    default: small
                    description: 'Supported sizes: small, medium, large'
                    type: string
                  version:
                    description: The DB version depends on the DB type and versions
                      available in the selected provider.
                    type: string
                required:
                - version
                type: object
              publishConnectionDetailsTo:
                properties:
                  configRef:
                    default:
                      name: default
                    properties:
                      name:
                        type: string
                    type: object
                  metadata:
                    properties:
                      annotations:
                        additionalProperties:
                          type: string
                        type: object
                      labels:
                        additionalProperties:
                          type: string
                        type: object
                      type:
                        type: string
                    type: object
                  name:
                    type: string
                required:
                - name
                type: object
              resourceRef:
                properties:
                  apiVersion:
                    type: string
                  kind:
                    type: string
                  name:
                    type: string
                required:
                - apiVersion
                - kind
                - name
                type: object
              writeConnectionSecretToRef:
                properties:
                  name:
                    type: string
                required:
                - name
                type: object
            required:
            - parameters
            type: object
          status:
            properties:
              conditions:
                description: Conditions of the resource.
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - lastTransitionTime
                  - reason
                  - status
                  - type
                  type: object
                type: array
              connectionDetails:
                properties:
                  lastPublishedTime:
                    format: date-time
                    type: string
                type: object
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    categories:
    - claim
    kind: SQLClaim
    listKind: SQLClaimList
    plural: sqlclaims
    singular: sqlclaim
  conditions:
  - lastTransitionTime: "2023-01-17T17:25:44Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2023-01-17T17:25:44Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1
